### ISSUE TITLE
Come up with admin API to get the BOSH director config for a giving service's BOSH deployment

### ISSUE THREAD

**Issue by kamath-prasad** [SAP/service-fabrik-broker#30]
**Problem Description**

- Currently after the support for Multi-BOSH - https://github.com/SAP/service-fabrik-broker/pull/7 the deployments for service instances could be created across any of the BOSH's configured . 
- Hence from a service's POV there is no single place to look for the BOSH where the deployment is present in order to verify the correctness of the deployment.

**Proposed Solution**

- Come up with a admin API in broker which takes the BOSH deployment name as input.
- Output should contain the details of the BOSH director under which the deployment is created.

**Comment by shashankmjain** [comment]
Can you please check if Services should be allowed to call back the Service Fabrik  broker. I had already raised this concern via email. Can you check this. As far as I remember the security groups are configured in a way, so that services cant call back the Broker. Must have been for a purpose. May be now we decided to change that.

**Comment by kamath-prasad** [comment]
@shashankmjain : This API would not be exposed to the services . Broker component will expose this functionality via scripts and services can only use it in their unit/integration tests with the broker.
