### ISSUE TITLE
Capability  for advance  debugging in case of travis build failures

### ISSUE THREAD

**Issue by ashishjain14** [SAP/service-fabrik-broker#42]

**Comment by akskap** [comment]
Motivation behind introducing advanced debugging is as follows:

- Validations ( Push / PR) can occasionally fail due to some problems with the code
- Some tests also dump information in the log files when the validation test runs
- Since TravisCI is a hosted solution, it does not offer access to execution environments by default
- With advanced debugging, user can re-run a failed test in 'Debug Mode' and get a link to a tmate session in the build logs
- By SSHing into the tmate session, a user can now control/mimic the TravisCI execution inside the container directly and traverse build steps one by one (install, after_install, script etc.)
- User can also access the additional files that are dumped with debugging information to better understand why the tests are failing

**Comment by akskap** [comment]
Enabled feature and added documentation @ https://github.com/SAP/service-fabrik-broker#advanced-debugging

**Comment by subhankarc** [comment]
@akskap  Please close it if PR already merged.
